### ISSUE TITLE
Problem with Database

### ISSUE THREAD

**Issue by hamid-gh** [nawarajkhadka/FoodmanduTroops#1]
I have a problem with FoodmanduTroops' DB. I attached DB and then run the application but an error occurred:
**Invalid object name 'dbo.Users'.
In the database, the table 'users' doesn't exists.
the following figure shows list of existing tables:

![image](https://cloud.githubusercontent.com/assets/11782611/12682588/796aa644-c6c9-11e5-83dc-b8d3853b4830.png)

**Comment by nawarajkhadka** [comment]
Try removing the Users table once and run the application. If you have any issues, i can forward the original database which I used to you.

**Comment by nawarajkhadka** [comment]
The user table is customizable. Please add a new user table in your
database as per your requirement. I have include the .edmx file in the
project for reference. You can use the user table in the edmx as reference
for creating db.
